services:
  my_project_db:
    image: postgres:15.2
    container_name: my_project_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  my_project_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_project_application
    restart: unless-stopped
    volumes:
      - ./backend:/app/src/
    env_file:
      - .env
    depends_on:
      - my_project_db
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork: